<a href="https://colab.research.google.com/github/vivaming/PyPractice/blob/master/DL_With_Python_Ch03_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
from keras.datasets import boston_housing

In [38]:
(train_data, train_targets), (test_data, test_targets) = boston_housing.load_data()

In [39]:
train_data.shape, test_data.shape

((404, 13), (102, 13))

data normalization

In [40]:
mean=train_data.mean(axis=0)

In [41]:
train_data-=mean
std=train_data.std(axis=0)
train_data /=std

In [42]:
test_data -=mean
test_data /=std




In [43]:
from keras import models
from keras import layers

In [44]:
# model=models.Sequential()
# model.add(layers.Dense(64, activation='relu', input_shape=(13,)))
# model.add(layers.Dense(64, activation='relu'))
# model.add(layers.Dense(1))

In [45]:
# model.compile(optimizer='rmsprop', 
#               loss='mse',
#               metrics=['mae'])

In [46]:
def build_model():
    model = models.Sequential()
    model.add(layers.Dense(64, activation='relu',
                           input_shape=(train_data.shape[1],)))
    model.add(layers.Dense(64, activation='relu'))
    model.add(layers.Dense(1))
    model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])
    return model

Given such a tiny training set - will apply a k-folder cross validation

In [47]:
import numpy as np

In [48]:
k=5
num_val_samples=len(train_data)//k

In [49]:
num_epochs=100
all_score=[]

In [50]:
for i in range(k):
  print ('Folder: ', i)
  val_data=train_data[i*num_val_samples:(i+1)*num_val_samples]
  val_targets=train_targets[i*num_val_samples:(i+1)*num_val_samples]
  # #testing the numpy slice range
  # print("val:", i*num_val_samples, ":", (i+1)*num_val_samples)
  # print("train1:", " :", i * num_val_samples )
  # print("train2:", (i + 1) * num_val_samples, ":")
  
  partial_train_data=np.concatenate(
      [train_data[:i*num_val_samples],
      train_data[(i+1)*num_val_samples:]], axis=0)
  partial_train_targets=np.concatenate(
      [train_targets[:i*num_val_samples],
      train_targets[(i+1)*num_val_samples:]], axis=0)
  print("train_size:", len(partial_train_data))

  model=build_model()
  model.fit(partial_train_data, partial_train_targets,
            epochs=num_epochs, batch_size=1)
  val_mse, val_mae=model.evaluate(val_data, val_targets)
  all_score.append(val_mae)

Folder:  0
train_size: 324
Epoch 1/100
324/324 [==============================] - 2s 2ms/step - loss: 178.0047 - mae: 9.8622
Epoch 2/100
324/324 [==============================] - 1s 2ms/step - loss: 25.1243 - mae: 3.4127
Epoch 3/100
324/324 [==============================] - 1s 2ms/step - loss: 19.9223 - mae: 2.9729
Epoch 4/100
324/324 [==============================] - 1s 2ms/step - loss: 18.2411 - mae: 2.8156
Epoch 5/100
324/324 [==============================] - 1s 2ms/step - loss: 16.6126 - mae: 2.6615
Epoch 6/100
324/324 [==============================] - 1s 2ms/step - loss: 15.5390 - mae: 2.5281
Epoch 7/100
324/324 [==============================] - 1s 2ms/step - loss: 14.7100 - mae: 2.4832
Epoch 8/100
324/324 [==============================] - 1s 2ms/step - loss: 13.8415 - mae: 2.4409
Epoch 9/100
324/324 [==============================] - 1s 2ms/step - loss: 12.9105 - mae: 2.4394
Epoch 10/100
324/324 [==============================] - 1s 2ms/step - loss: 13.2883 - mae: 2.3152
E

In [51]:
np.mean(all_score)

2.4897117614746094

In [52]:
all_score

[2.1482088565826416,
 2.722872018814087,
 2.265690565109253,
 2.7459819316864014,
 2.565805435180664]

In [53]:
train_targets

array([15.2, 42.3, 50. , 21.1, 17.7, 18.5, 11.3, 15.6, 15.6, 14.4, 12.1,
       17.9, 23.1, 19.9, 15.7,  8.8, 50. , 22.5, 24.1, 27.5, 10.9, 30.8,
       32.9, 24. , 18.5, 13.3, 22.9, 34.7, 16.6, 17.5, 22.3, 16.1, 14.9,
       23.1, 34.9, 25. , 13.9, 13.1, 20.4, 20. , 15.2, 24.7, 22.2, 16.7,
       12.7, 15.6, 18.4, 21. , 30.1, 15.1, 18.7,  9.6, 31.5, 24.8, 19.1,
       22. , 14.5, 11. , 32. , 29.4, 20.3, 24.4, 14.6, 19.5, 14.1, 14.3,
       15.6, 10.5,  6.3, 19.3, 19.3, 13.4, 36.4, 17.8, 13.5, 16.5,  8.3,
       14.3, 16. , 13.4, 28.6, 43.5, 20.2, 22. , 23. , 20.7, 12.5, 48.5,
       14.6, 13.4, 23.7, 50. , 21.7, 39.8, 38.7, 22.2, 34.9, 22.5, 31.1,
       28.7, 46. , 41.7, 21. , 26.6, 15. , 24.4, 13.3, 21.2, 11.7, 21.7,
       19.4, 50. , 22.8, 19.7, 24.7, 36.2, 14.2, 18.9, 18.3, 20.6, 24.6,
       18.2,  8.7, 44. , 10.4, 13.2, 21.2, 37. , 30.7, 22.9, 20. , 19.3,
       31.7, 32. , 23.1, 18.8, 10.9, 50. , 19.6,  5. , 14.4, 19.8, 13.8,
       19.6, 23.9, 24.5, 25. , 19.9, 17.2, 24.6, 13

In [54]:
model.predict(test_data)[1:20], test_targets[1:20]

(array([[18.419003],
        [19.923273],
        [31.257807],
        [23.359201],
        [24.078377],
        [27.138084],
        [21.704859],
        [19.475752],
        [20.182777],
        [21.91485 ],
        [17.618853],
        [14.707965],
        [44.15093 ],
        [23.543776],
        [21.238424],
        [24.087183],
        [23.403898],
        [19.636564],
        [26.32152 ]], dtype=float32),
 array([18.8, 19. , 27. , 22.2, 24.5, 31.2, 22.9, 20.5, 23.2, 18.6, 14.5,
        17.8, 50. , 20.8, 24.3, 24.2, 19.8, 19.1, 22.7]))

In [55]:
import matplotlib.pyplot as plt
